[package]
name = "image-resize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-watch = "8.1.2"

[dev-dependencies]
wasm-bindgen-test = "0.3.33"
